version: '2'

services:
    killingfloor2:
        container_name: killingfloor2
        image: dwurf/docker-kf2:latest
        #Uncomment this to skip auto-update
        #command: update validate
        #command: update -beta preview validate
        restart: always
        ports:
            - 20560:20560/udp
            - 27015:27015/udp
            - 7777:7777/udp
            - 8081:8080
        environment:
            - KF_DIFFICULTY=1
            - KF_DISABLE_TAKEOVER=false
            - KF_ENABLE_WEB=true
            - KF_GAME_LENGTH=1
            - KF_MAP=KF-BioticsLab
        volumes:
            - /home/izzuthug/KillingFloor2:/home/steam/kf2server 
            - /home/izzuthug/KillingFloor2/steam:/home/steam/steam
            - /home/izzuthug/KillingFloor2/Binaries/Win64/steamapps:/home/steam/kf2server/Binaries/Win64/steamapps
            - /home/izzuthug/KillingFloor2/KFGame/Cache:/home/steam/kf2server/KFGame/Cache
            #- /home/izzuthug/KillingFloor2/game.yml:/home/steam/game.yml:ro
        logging:
            # limit logs retained on host to 25MB
            driver: "json-file"
            options:
                max-size: "500k"
                max-file: "50"
